### ISSUE TITLE
Relation to liip/RMT?

### ISSUE THREAD

**Issue by ShonM** [bonndan/release-manager#16]
This looks just like another tool I was looking at: https://github.com/liip/RMT

Is this some kind of fork/clone? Is that other repository a fork/clone? It seems to have more following, but this project has more recent updates. Not sure which to try out yet.

**Comment by bonndan** [comment]
This is a fork from RMT, mainly because RMT has to many features for my taste and is quite hard to maintain. However, I am not sure anymore if this way of handling versions is right, because it is more or less complicated to use. In PHP projects I've been using git flow for a year now without any sugar on top (had no choice) and I today don't really miss release-manager.
